name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/step-setup

      - name: Run build
        run: npm run ci:build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/step-setup

      - name: Run tests
        run: npm run ci:test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/step-setup

      - name: Run lint
        run: npm run ci:lint

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/step-setup

      - name: Run E2E
        run: npm run ci:e2e
